version: '2'
services:
  influxdb:
    image: influxdb:1.8
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    build: grafana/
    ports:
      - '3026:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  pinger:
    build: pinger/
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
      - PING_HOSTS=${PING_HOSTS}
  speedtest:
    image: robinmanuelthiel/speedtest:latest
    restart: always
    environment:
      - LOOP=true
      - LOOP_DELAY=1800
      - DB_SAVE=true
      - DB_HOST=influxdb
      - DB_NAME=${INFLUXDB_DATABASE}
      - DB_USERNAME=${INFLUXDB_USERNAME}
      - DB_PASSWORD=${INFLUXDB_PASSWORD}
    privileged: true # Needed for 'sleep' in the loop
    depends_on:
      - influxdb
volumes:
  influxdb-storage:
  grafana-storage:
